### ISSUE TITLE
fFtT Not working (Catalina)

### ISSUE THREAD

**Issue by rkabrick** [dbalatero/VimMode.spoon#17]
The keys fFtT are not working for me under Catalina. I wasn't able to test under Mojave but I wasn't sure if there was any easy fix to repair the functionality. Instead of searching forward/backward, it simply just inserts the respective letter pushed

**Comment by dbalatero** [comment]
@rkabrick Hi! Those don't work currently on v1. The reason is that the v1 of the plugin (master) does not have any context on what text it is editing - it flies blind by issuing keyboard commands to do common movement/selection/delete operations.

However! My v2 branch `vim-mode-v2` is almost ready to start beta testing. I will definitely be implementing those motions soon, as I use them a lot. I am hooking the OS X Accessibility API to gain more context of what is being edited, so this will be possible going forward. I am closing this as it's work on my horizon soon and the README already calls out that they are unsupported in master.
