### ISSUE TITLE
Force fallback for apps?

### ISSUE THREAD

**Issue by normen** [dbalatero/VimMode.spoon#83]
Hey, first of all thanks for this software, I love it!

I was wondering if theres a way to force fallback mode for a whole app instead of "just" URLs as described in #71

Specifically, when I enable vim-mode in Dwarf Fortress I can (finally) scroll around with hjkl but they key strokes are delayed somehow, I suspect thats due to VimMode.spoon trying to figure out if it can use advanced mode over and over again on each keypress (?) So my naive idea is to simply tell VimMode.spoon to only use fallback mode for Dwarf Fortress to get quicker reaction time.

If theres no such option I could try and implement it given some pointers on where and how to add this.

Cheers,
Normen

**Comment by dbalatero** [comment]
OMG this is my first "doesn't work in Dwarf Fortress" bug report, so that's great news!

I can definitely expose a config option for enforcing fallback mode - something like `vim:useFallbackMode('Dwarf Fortress')`.

Before I do that, can you do the following:

1. Add something like `"Dwarf Fortress" = true,` to [this file](https://github.com/dbalatero/VimMode.spoon/blob/48f01eec5bf7ac4e494efe8b92281827251c510b/lib/accessibility_buffer.lua#L13-L30).
2. Save + reload Hammerspoon
3. See if it helps

Thanks!

**Comment by normen** [comment]
Hm, LUA complains about the syntax when I use `"Dwarf Fortress" = true,` - same when I use `dwarfort.exe = true,` (without quotes but with a dot) or `Dwarf Fortress = true,` (without quotes, with space).

Using `DwarfFortress = true,`, `Dwarf = true,` or `Fortress = true,`  (no quotes, no space) runs but doesn't seem to change the behavior.

Thanks for the quick reply!

**Comment by dbalatero** [comment]
What is the name of the application in the upper left corner of the Mac?

![image](https://user-images.githubusercontent.com/59429/124677202-e80f3d80-de8d-11eb-880c-a4b9a8a80f5b.png)

Also what's the name in Activity Monitor?

![image](https://user-images.githubusercontent.com/59429/124677226-f4939600-de8d-11eb-9336-0f6f98ecd642.png)

If it turns out to be `Dwarf Fortress`, the correct Lua syntax is actually:

```lua
local banned = {
  ["Dwarf Fortress"] = true,
}
```

**Comment by normen** [comment]
Ha, that was it. The name in the menu bar is actually - for whatever reason even on mac - `dwarfort.exe`. The title bar on the Window itself reads "Dwarf Fortress" but adding `["dwarfort.exe"] = true` yields the desired result. Thanks!

**Comment by dbalatero** [comment]
Great, sounds like a `vim:useFallbackMode('dwarfort.exe')` API would be useful to expose so you don't have to hack this into the banned apps list. I can probably get to that in the next few weeks.

**Comment by dbalatero** [comment]
@normen 
This is available now in master:

```lua
vim:useFallbackMode('dwarfort.exe')
```

**Comment by normen** [comment]
Weee, thanks!
